### PR TITLE
Update eslint and eslint-config-stylelint dependancies

### PR DESCRIPTION
**Pull request by ntwb**

### CODE REVIEW

**Comment by ntwb** [comment]
When in Rome, as they say, updates `stylelint-config-cssrecipes` to use AVA for tests (This brings this repo to the same configuration for tests for the other `stylelint-config-standard`, `stylelint-config-suitcss`, and `stylelint-config-wordpress` repos)

**Comment by ntwb** [comment]
It also fix the failing tests :smirk:

**Comment by MoOx** [comment]
:+1: Thanks !

**Comment by magsout** [comment]
Nice, thanks

**Pull request merged**
