### PR TITLE
Fix indentation definition

### LINKED ISSUE #8: Doesn't work with gulp-postcss
``` js
[01:58:05] TypeError in plugin 'gulp-postcss'
Message:
    Object.keys called on non-object
```

With standard config everything fine. Maybe some rules somehow break warnings?

### PR DESCRIPTION
**Pull request by TrySound**
fix #8

### CODE REVIEW

**Comment by jeddy3** [comment]
Thanks!

**Comment by jeddy3** [comment]
@magsout When you have a moment, can you `npm publish` on master please? I've done a github release.

**Comment by magsout** [comment]
@jeddy3 done, what's you login on npm website ?

**Comment by jeddy3** [comment]
`jeddy3` :)

**Comment by magsout** [comment]
thanks @TrySound

**Comment by magsout** [comment]
@jeddy3 added

**Pull request merged**
