### PR TITLE
Stylelint v3

### PR DESCRIPTION
**Pull request by ntwb**
- Removed: `stylelint < 3.0.0` compatibility.
  - Changed: configuration syntax.
  - Changed: renamed the `function-space-after` rule to `function-whitespace-after`.
  - Changed: renamed the `no-multiple-empty-lines` rule to `max-empty-lines` with value `1`
- Added initial tests
- Changed from standalone eslint configuration to stylelint orginization shared `eslint-config-stylelint` configuration

### CODE REVIEW

**Comment by jeddy3** [comment]
@ntwb Thanks for doing this, especially as it's a config you're unlikely using yourself!

I merged in your other PR (the eslint one) before seeing this one, and now there are conflicts as the eslint changes are duplicated in this PR. Can you rebase/resolve the conflict and then I'm happy to see this merged in, if @magsout is?

**Comment by magsout** [comment]
thanks again @ntwb . If you can rebase and squash please.

yes go @jeddy3  ;) thanks

**Comment by ntwb** [comment]
I think I got the upstream merge right :smirk: 

Yeah, so I've lots of JS to learn, so learning by example :+1: 

It also bought me up to speed for stylelint v3 changes that went into `stylelint-config-wordpress` :smile:

**Comment by jeddy3** [comment]
@ntwb Looks great thanks!

@magsout Are you able to cut the `2.0.0` release here and on npm?

**Comment by magsout** [comment]
Thanks to both of you 

And yes @jeddy3 I will released this afternoon

**Comment by ntwb** [comment]
Awesome :+1:

**Comment by magsout** [comment]
Released and published on npm :+1:

**Comment by jeddy3** [comment]
Thanks! :)

**Comment by ntwb** [comment]
:+1:

**Pull request merged**
